### GET LIST OF PRODUCTS
GET http://localhost:8080/api/v1/products?limit=5 HTTP/1.1

### GET A PRODUCT
GET http://localhost:8080/api/v1/products/6635db7d414e2067475ba5f1 HTTP/1.1

### ADD A NEW PRODUCT
POST http://localhost:8080/api/v1/products HTTP/1.1
Content-Type: application/json

{
    "product": {
        "title": "Other",
        "description": "One",
        "price": 10.5,
        "stock": 20,
        "code": "client10",
        "other": "value"
    }
}

### UPDATE A PRODUCT
PUT http://localhost:8080/api/v1/products/662ea0e9fef5300a89002403 HTTP/1.1
Content-Type: application/json

{
    "product": {
        "title": "ggggg",
        "code": "client200"
    }
    
}

### DELETE A PRODUCT
DELETE http://localhost:8080/api/v1/products/6635ca925d173e5ecd10952f HTTP/1.1



### GET PRODUCTS OF A CART
GET http://localhost:8080/api/v1/carts/6637dc5d5546f757167ef005 HTTP/1.1

### ADDS NEW CART
POST http://localhost:8080/api/v1/carts HTTP/1.1

### ADDS A PRODUCT WITH ITS QUANTITY TO A CART
POST http://localhost:8080/api/v1/carts/663809c890b09e7075e29e6c/products/6636c037b320bf869effa0a6 HTTP/1.1
Content-Type: application/json

{
    "quantity": "-10"
}

### REMOVES A PRODUCT FROM A CART
DELETE http://localhost:8080/api/v1/carts/663809c890b09e7075e29e6c/products/6636c037b320bf869effa0a6 HTTP/1.1