version: '3.9'
services:
  express-backend:
    image: express-backend:dev
    container_name: express-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    command:
    - sh
    - -c
    - tail -f /dev/null
    init: true
    ports:
      - "${HOST_SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    volumes:
      - ./src:/app/src