version: '3.9'
services:
  mongo:
    image: mongodb/mongodb-community-server:5.0.11-ubuntu2004
    container_name: mongo-docker
    restart: always
    ports:
      - "${HOST_DB_PORT:-27017}:27017"
    volumes:
      - mongodata:/data/db

  server:
    image: server:local
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    restart: always
    # command:
    # - sh
    # - -c
    # - tail -f /dev/null
    init: true
    ports:
      - "${HOST_SERVER_PORT:-8080}:${SERVER_PORT:-8080}"

  websocket-server:
    image: websocket-server:local
    container_name: websocket-server
    build:
      context:  ./socketServer
      dockerfile: Dockerfile
    restart: always
    init: true
    ports:
      - "${HOST_WS_SERVER_PORT:-3000}:${WS_PORT:-3000}"
    
volumes:
  mongodata: