version: '3.9'
services:
  mongo:
    image: mongodb/mongodb-community-server:5.0.11-ubuntu2004
    container_name: mongo-docker
    restart: always
    ports:
      - "${HOST_DB_PORT:-27017}:27017"
    volumes:
      - mongodata:/data/db

  server:
    image: server:local
    container_name: server-local
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    restart: always
    init: true
    ports:
      - "${HOST_SERVER_PORT:-8080}:${SERVER_PORT}"
volumes:
  mongodata: