kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        tier: database
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:5.0.11-ubuntu2004
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        startupProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        command:
        - mongod
        - --bind_ip_all
        - --config=/etc/mongo/mongodb.conf
        volumeMounts:
        - name: mongodb-data-vol
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongo
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
          items:
          - key: mongodb.conf
            path: mongodb.conf
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
