# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mongodata-pv
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: mongodb
    svc: mongodb-service
spec:
  nodeSelector:
    tier: database
  containers:
  - name: mongodb
    image: mongodb/mongodb-community-server:5.0.11-ubuntu2004
    ports:
    - containerPort: 27017
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    volumeMounts:
    - name: mongodata-volume
      mountPath: /data/db
  volumes:
  - name: mongodata-volume
    persistentVolumeClaim:
      claimName: mongodata-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

