kind: Deployment
apiVersion: apps/v1
metadata:
  name: ecommerce-api
  labels:
    app: ecommerce-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # a maximum of 1 pod can be being created at the same time
      maxUnavailable: 0 # there can be no unavailable pods
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      nodeSelector:
        tier: server
      containers:
      - name: ecommerce-api
        image: bolanosnava/ecommerce-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: ecommerce-env
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "1.25Gi"

