kind: Pod
apiVersion: v1
metadata:
  name: ecommerce-api
  labels:
    app: ecommerce-api
    svc: ecommerce-api-svc
spec:
  nodeSelector:
    tier: server
  containers:
  - name: ecommerce-api
    image: bolanosnava/ecommerce-api:latest
    ports:
    - containerPort: 8080 # we are defining port 8080 as the one that will be exposed
    # command to keep container alive while idle
    # command:
    # - sh
    # - -c
    # - tail -f /dev/null

    # We are loading envs from the secret we created, called ecommerce-env. This secret should be created from the .env file of whoever wants to deploy this cluster, so as to keep the .env file from being embedded into the Docker image
    envFrom:
    - secretRef:
        name: ecommerce-env
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
