kind: Deployment
apiVersion: apps/v1
metadata:
  name: express-server-deployment
  labels:
    app: express-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: express-server
    spec:
      nodeSelector:
        tier: server
      containers:
      - name: express-server
        image: bolanosnava/express-server:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: server-env
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "1.25Gi"

