kind: Deployment
apiVersion: apps/v1
metadata:
  name: express-server-deployment
  labels:
    app: express-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      nodeSelector:
        tier: server
      containers:
      - name: express-server
        image: bolanosnava/express-server:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: server-env
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

